// Package msgidgen 从源语言目录生成 internal/msgid 的消息常量。只在构建期用（cmd/gen-msgid、
// 检查测试、tools/i18n），CLI 运行时不引用它。
package msgidgen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// initialisms 是写成全大写的词（Go 的惯例：ID、JSON、URL……）。
var initialisms = map[string]bool{
	"id": true, "json": true, "yaml": true, "url": true, "http": true, "https": true, "api": true, "dns": true,
	"tls": true, "cpu": true, "io": true, "sa": true, "pr": true, "ci": true, "ui": true, "uid": true, "pid": true,
	"tcp": true, "udp": true, "ssh": true, "oci": true, "utf8": true, "cidr": true,
}

// GoName 是 key 对应的常量名：按 . 与 _ 切开，每段首字母大写，缩写词全大写。
func GoName(key string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(key, func(r rune) bool { return r == '.' || r == '_' }) {
		if initialisms[part] {
			b.WriteString(strings.ToUpper(part))
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

// SourceKeys 按文件顺序读出目录文件里的 key。
func SourceKeys(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	if len(doc.Content) == 0 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, fmt.Errorf("%s: not a mapping of key: text", path)
	}
	root := doc.Content[0]
	keys := make([]string, 0, len(root.Content)/2)
	for i := 0; i+1 < len(root.Content); i += 2 {
		keys = append(keys, root.Content[i].Value)
	}
	return keys, nil
}

// PluralOneSuffix 与 msgid.PluralOneSuffix 相同；msgidgen 不引用 msgid，免得生成器依赖被生成的包。
const PluralOneSuffix = ".one"

// Render 生成 messages_gen.go 的源码。
func Render(keys []string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-msgid; DO NOT EDIT.\n")
	b.WriteString("// 源：internal/i18n/locales/en.yaml。增删消息改目录，再跑 make generate-msgid。\n\n")
	b.WriteString("package msgid\n\nconst (\n")
	owner := map[string]string{}
	for _, key := range keys {
		if strings.HasSuffix(key, PluralOneSuffix) {
			continue
		}
		name := GoName(key)
		if prev, dup := owner[name]; dup {
			return nil, fmt.Errorf("keys %q and %q both become the Go name %s", prev, key, name)
		}
		owner[name] = key
		fmt.Fprintf(&b, "\t%s ID = %q\n", name, key)
	}
	b.WriteString(")\n")
	return format.Source(b.Bytes())
}
