package msgid

// internal/cli/login.go
const (
	CliLoginPassword                         = "cli.login.password"
	CliLoginUserName                         = "cli.login.user_name"
	CliLoginLoggedIn                         = "cli.login.logged_in"
	CliLoginErrorThePasswordMustNot          = "cli.login.error_the_password_must_not"
	CliLoginErrorFailedToReadThe             = "cli.login.error_failed_to_read_the"
	CliLoginErrorFailedToReadThe2            = "cli.login.error_failed_to_read_the_2"
	CliLoginLoggingInToTheBrickkit           = "cli.login.logging_in_to_the_brickkit"
	CliLoginUserName2                        = "cli.login.user_name_2"
	CliLoginErrorTheUserNameMust             = "cli.login.error_the_user_name_must"
	CliLoginMarketAddress                    = "cli.login.market_address"
	CliLoginCheckTheUserNameAnd              = "cli.login.check_the_user_name_and"
	CliLoginIfYouForgotThePassword           = "cli.login.if_you_forgot_the_password"
	CliLoginErrorNoReadableStandardInput     = "cli.login.error_no_readable_standard_input"
	CliLoginOrSpecifyTheMarketAddress        = "cli.login.or_specify_the_market_address"
	CliLoginUserNameAskedInteractivelyIf     = "cli.login.user_name_asked_interactively_if"
	CliLoginSpecifyOneOfTheMarket            = "cli.login.specify_one_of_the_market"
	CliLoginRunBrickkitLoginAgainAnd         = "cli.login.run_brickkit_login_again_and"
	CliLoginErrorCannotDetermineWhichMarket  = "cli.login.error_cannot_determine_which_market"
	CliLoginRunBrickkitLoginAgainAnd2        = "cli.login.run_brickkit_login_again_and_2"
	CliLoginErrorLoginFailedWrongUser        = "cli.login.error_login_failed_wrong_user"
	CliLoginShort                            = "cli.login.short"
	CliLoginErrorBrickkitYamlHasNo           = "cli.login.error_brickkit_yaml_has_no"
	CliLoginValidUntil                       = "cli.login.valid_until"
	CliLoginTheCurrentDirectoryIsNot         = "cli.login.the_current_directory_is_not"
	CliLoginReadThePasswordFromStandard      = "cli.login.read_the_password_from_standard"
	CliLoginMarketAddressDefaultsToThe       = "cli.login.market_address_defaults_to_the"
	CliLoginAddAnInstallSourceOf             = "cli.login.add_an_install_source_of"
	CliLoginErrorSeveralMarketInstallSources = "cli.login.error_several_market_install_sources"
	CliLoginTokenStoredAt                    = "cli.login.token_stored_at"
	CliLoginRunBrickkitLoginInA              = "cli.login.run_brickkit_login_in_a"
	CliLoginSpecifyTheMarketAddressWith      = "cli.login.specify_the_market_address_with"
	CliLoginLong                             = "cli.login.long"
)
