package msgid

// internal/cli/publish.go
const (
	CliPublishMarket                                      = "cli.publish.market"
	CliPublishCurrentValue                                = "cli.publish.current_value"
	CliPublishAllowedValues                               = "cli.publish.allowed_values"
	CliPublishArtifactType                                = "cli.publish.artifact_type"
	CliPublishLookedAt                                    = "cli.publish.looked_at"
	CliPublishStatusOnTheMarket                           = "cli.publish.status_on_the_market"
	CliPublishPublished                                   = "cli.publish.published"
	CliPublishUploadSucceeded                             = "cli.publish.upload_succeeded"
	CliPublishReleaseNotesForThisVersion                  = "cli.publish.release_notes_for_this_version"
	CliPublishManifestValidationPassed                    = "cli.publish.manifest_validation_passed"
	CliPublishGitRepository                               = "cli.publish.git_repository"
	CliPublishVisibility                                  = "cli.publish.visibility"
	CliPublishErrorPublishingFailedNotLogged              = "cli.publish.error_publishing_failed_not_logged"
	CliPublishSignTheComponentWithCosign                  = "cli.publish.sign_the_component_with_cosign"
	CliPublishErrorFailedToReadComponent                  = "cli.publish.error_failed_to_read_component"
	CliPublishErrorInvalidVisibilityValue                 = "cli.publish.error_invalid_visibility_value"
	CliPublishSourceType                                  = "cli.publish.source_type"
	CliPublishErrorComponentYamlIsNot                     = "cli.publish.error_component_yaml_is_not"
	CliPublishComponentSourceDirectoryContainingComponent = "cli.publish.component_source_directory_containing_component"
	CliPublishErrorTheMarketHasNo                         = "cli.publish.error_the_market_has_no"
	CliPublishErrorAFileDeclaredUnder                     = "cli.publish.error_a_file_declared_under"
	CliPublishErrorComponentYamlCouldNot                  = "cli.publish.error_component_yaml_could_not"
	CliPublishSignerIdentifierForExampleRelease           = "cli.publish.signer_identifier_for_example_release"
	CliPublishErrorThereIsNoComponent                     = "cli.publish.error_there_is_no_component"
	CliPublishOrSpecifyWhichMarketTo                      = "cli.publish.or_specify_which_market_to"
	CliPublishShort                                       = "cli.publish.short"
	CliPublishOrConfigureSourcesAuthtokenIn               = "cli.publish.or_configure_sources_authtoken_in"
	CliPublishPathOfTheCosignPrivate                      = "cli.publish.path_of_the_cosign_private"
	CliPublishOrCorrectThePathUnder                       = "cli.publish.or_correct_the_path_under"
	CliPublishMakeSureTheMarketService                    = "cli.publish.make_sure_the_market_service"
	CliPublishPointPathAtTheComponent                     = "cli.publish.point_path_at_the_component"
	CliPublishVisibilityPublicPrivateDefaultsTo           = "cli.publish.visibility_public_private_defaults_to"
	CliPublishMakeSureTheFileHas                          = "cli.publish.make_sure_the_file_has"
	CliPublishImageReferenceIsValid                       = "cli.publish.image_reference_is_valid"
	CliPublishIfYouOnlyWantTo                             = "cli.publish.if_you_only_want_to"
	CliPublishUseAnotherVersionNumberChange               = "cli.publish.use_another_version_number_change"
	CliPublishGitRepositoryAddressOfAn                    = "cli.publish.git_repository_address_of_an"
	CliPublishArtifactsUploadedFiles                      = "cli.publish.artifacts_uploaded_files"
	CliPublishOncePublishedAVersionNumber                 = "cli.publish.once_published_a_version_number"
	CliPublishPublicKeyRefWrittenInto                     = "cli.publish.public_key_ref_written_into"
	CliPublishTheArchiveDirectoryWorksToo                 = "cli.publish.the_archive_directory_works_too"
	CliPublishPublishing                                  = "cli.publish.publishing"
	CliPublishComponent                                   = "cli.publish.component"
	CliPublishIfYouReallyWantTo                           = "cli.publish.if_you_really_want_to"
	CliPublishResumingThisVersionWasCreated               = "cli.publish.resuming_this_version_was_created"
	CliPublishErrorHasAlreadyBeenPublished                = "cli.publish.error_has_already_been_published"
	CliPublishSourceTypeGitOpenSource                     = "cli.publish.source_type_git_open_source"
	CliPublishDonTPinTheImage                             = "cli.publish.don_t_pin_the_image"
	CliPublishErrorWasCreatedLastTime                     = "cli.publish.error_was_created_last_time"
	CliPublishResumingCanOnlyUploadThe                    = "cli.publish.resuming_can_only_upload_the"
	CliPublishExample                                     = "cli.publish.example"
	CliPublishLong                                        = "cli.publish.long"
)
