package msgid

// internal/cli/remove.go
const (
	CliRemoveDependent                              = "cli.remove.dependent"
	CliRemoveCurrentVersion                         = "cli.remove.current_version"
	CliRemoveCurrentComponents                      = "cli.remove.current_components"
	CliRemoveRemoveTheDependentsFirst               = "cli.remove.remove_the_dependents_first"
	CliRemoveCleanTheManifestCache                  = "cli.remove.clean_the_manifest_cache"
	CliRemoveCleanTheArtifactsCache                 = "cli.remove.clean_the_artifacts_cache"
	CliRemoveTheseComponentsDependOnIt              = "cli.remove.these_components_depend_on_it"
	CliRemoveRemoveComponentIdVersion               = "cli.remove.remove_component_id_version"
	CliRemoveRemoved                                = "cli.remove.removed"
	CliRemovePleaseSpecifyTheComponentTo            = "cli.remove.please_specify_the_component_to"
	CliRemoveCheckTheFileAndDirectory               = "cli.remove.check_the_file_and_directory"
	CliRemoveCheckThatTheComponentId                = "cli.remove.check_that_the_component_id"
	CliRemoveBrickkitRemoveComponentIdVersion       = "cli.remove.brickkit_remove_component_id_version"
	CliRemoveOptionalDependencyDegradationIsHandled = "cli.remove.optional_dependency_degradation_is_handled"
	CliRemoveCleanedTheManifestCache                = "cli.remove.cleaned_the_manifest_cache"
	CliRemoveCleanedTheArtifactsCache               = "cli.remove.cleaned_the_artifacts_cache"
	CliRemoveErrorTheSourceCanT                     = "cli.remove.error_the_source_can_t"
	CliRemoveWarningIsDependedOnAs                  = "cli.remove.warning_is_depended_on_as"
	CliRemoveBrickkitYamlHasNoSuch                  = "cli.remove.brickkit_yaml_has_no_such"
	CliRemoveWarningCannotConfirmTheDependencies    = "cli.remove.warning_cannot_confirm_the_dependencies"
	CliRemoveShort                                  = "cli.remove.short"
	CliRemoveCannotRemove                           = "cli.remove.cannot_remove"
	CliRemoveResourceBindingsDropped                = "cli.remove.resource_bindings_dropped"
	CliRemoveIfYouAreSureYou                        = "cli.remove.if_you_are_sure_you"
	CliRemoveDeletedSourceDirectory                 = "cli.remove.deleted_source_directory"
	CliRemoveThatComponentSManifestIs               = "cli.remove.that_component_s_manifest_is"
	CliRemoveErrorIsNotInBrickkit                   = "cli.remove.error_is_not_in_brickkit"
	CliRemoveFirstKeepItSafeCommit                  = "cli.remove.first_keep_it_safe_commit"
	CliRemoveCheckThatTheVersionNumber              = "cli.remove.check_that_the_version_number"
	CliRemoveDeletedArchivedSourceDirectory         = "cli.remove.deleted_archived_source_directory"
	CliRemoveErrorIsNotInBrickkit2                  = "cli.remove.error_is_not_in_brickkit_2"
	CliRemoveRunBrickkitAddToPull                   = "cli.remove.run_brickkit_add_to_pull"
	CliRemoveCannotTellWhetherItDepends             = "cli.remove.cannot_tell_whether_it_depends"
	CliRemoveExample2                               = "cli.remove.example_2"
	CliRemoveDeleteTheSourceEvenWhen                = "cli.remove.delete_the_source_even_when"
	CliRemoveHasSeveralVersionsPleaseSpecify        = "cli.remove.has_several_versions_please_specify"
	CliRemoveAfterRemovalTheEnvironmentVariable     = "cli.remove.after_removal_the_environment_variable"
	CliRemoveIfYouOnlyDonT                          = "cli.remove.if_you_only_don_t"
	CliRemoveLong                                   = "cli.remove.long"
)
