package msgid

// internal/cli/add.go
const (
	CliAddAddComponentIdExactVersion = "cli.add.add_component_id_exact_version"
	CliAddShort                      = "cli.add.short"
	CliAddLong                       = "cli.add.long"
	CliAddExample                    = "cli.add.example"
	CliAddFlagYes                    = "cli.add.flag_yes"
	CliAddFlagRepo                   = "cli.add.flag_repo"
	CliAddFlagRepoAll                = "cli.add.flag_repo_all"
	CliAddFlagLocal                  = "cli.add.flag_local"
	CliAddNeedsComponent             = "cli.add.needs_component"
	CliAddHintNeedsComponent         = "cli.add.hint_needs_component"
	CliAddResolvedLatest             = "cli.add.resolved_latest"
	CliAddNothingChanged             = "cli.add.nothing_changed"
	CliAddHeader                     = "cli.add.header"
	CliAddLine                       = "cli.add.line"
	CliAddLineRequiredBy             = "cli.add.line_required_by"
	CliAddLineInShell                = "cli.add.line_in_shell"
	CliAddLineRequiredByInShell      = "cli.add.line_required_by_in_shell"
	CliAddNested                     = "cli.add.nested"
	CliAddRequiredByExtended         = "cli.add.required_by_extended"
	CliAddConfigsWritten             = "cli.add.configs_written"
	CliAddConfigRestored             = "cli.add.config_restored"
	CliAddArtifacts                  = "cli.add.artifacts"
	CliAddSignatureVerified          = "cli.add.signature_verified"
	CliAddVarPrompt                  = "cli.add.var_prompt"
	CliAddVarReferenced              = "cli.add.var_referenced"
	CliAddCloneSkippedNoRepo         = "cli.add.clone_skipped_no_repo"
	CliAddCloneAfterWrite            = "cli.add.clone_after_write"
	CliAddCloned                     = "cli.add.cloned"
	CliAddLocalNoLocalSource         = "cli.add.local_no_local_source"
	CliAddLocalHintConfigureLocal    = "cli.add.local_hint_configure_local"
	CliAddLocalProblem               = "cli.add.local_problem"
	CliAddLocalVersionDiffers        = "cli.add.local_version_differs"
	CliAddLocalNothingToAdd          = "cli.add.local_nothing_to_add"
	CliAddLocalTakesNoComponent      = "cli.add.local_takes_no_component"
	CliAddLocalHintOneComponent      = "cli.add.local_hint_one_component"
	CliAddLocalWithRepo              = "cli.add.local_with_repo"
	CliInstallWritten                = "cli.install.written"
	CliInstallNote                   = "cli.install.note"
	CliInstallOtherDeployFiles       = "cli.install.other_deploy_files"
	CliInstallWouldBreakProject      = "cli.install.would_break_project"
	CliInstallHintFixFirst           = "cli.install.hint_fix_first"
	CliInstallTargetExists           = "cli.install.target_exists"
	CliInstallProjectDocFailed       = "cli.install.project_doc_failed"
)
