package msgid

const (
	CliLocalShort            = "cli.local.short"
	CliLocalLong             = "cli.local.long"
	CliLocalExample          = "cli.local.example"
	CliLocalOnShort          = "cli.local.on_short"
	CliLocalOffShort         = "cli.local.off_short"
	CliLocalStatusShort      = "cli.local.status_short"
	CliLocalRefreshShort     = "cli.local.refresh_short"
	CliLocalNoDeployFile     = "cli.local.no_deploy_file"
	CliLocalHintInit         = "cli.local.hint_init"
	CliLocalAlreadyOn        = "cli.local.already_on"
	CliLocalOn               = "cli.local.on"
	CliLocalCopied           = "cli.local.copied"
	CliLocalReused           = "cli.local.reused"
	CliLocalHintRefresh      = "cli.local.hint_refresh"
	CliLocalAlreadyOff       = "cli.local.already_off"
	CliLocalOff              = "cli.local.off"
	CliLocalFileKept         = "cli.local.file_kept"
	CliLocalStateOn          = "cli.local.state_on"
	CliLocalStateOff         = "cli.local.state_off"
	CliLocalStatusMode       = "cli.local.status_mode"
	CliLocalStatusFileNone   = "cli.local.status_file_none"
	CliLocalStatusFileInUse  = "cli.local.status_file_in_use"
	CliLocalStatusFileIdle   = "cli.local.status_file_idle"
	CliLocalStatusConsistent = "cli.local.status_consistent"
	CliLocalNothingToRefresh = "cli.local.nothing_to_refresh"
	CliLocalHintOn           = "cli.local.hint_on"
	CliLocalRefreshed        = "cli.local.refreshed"
	CliLocalBackupReplaced   = "cli.local.backup_replaced"
	CliLocalDiffFailed       = "cli.local.diff_failed"
	CliLocalNoChanges        = "cli.local.no_changes"
	CliLocalChangesHeader    = "cli.local.changes_header"
	CliLocalChangeEntryGone  = "cli.local.change_entry_gone"
	CliLocalChangeUnset      = "cli.local.change_unset"
	CliLocalChangeDiffers    = "cli.local.change_differs"
	CountLocalChanges        = "count.local_changes"
	CliLocalTeamFileInvalid  = "cli.local.team_file_invalid"
	CliLocalHintFixTeamFile  = "cli.local.hint_fix_team_file"
	CliLocalAlreadyFresh     = "cli.local.already_fresh"
)
