package msgid

// internal/cli/restore.go
const (
	CliRestoreShort                            = "cli.restore.short"
	CliRestoreLong                             = "cli.restore.long"
	CliRestoreExample                          = "cli.restore.example"
	CliRestoreOnlyCheckWhetherTheYaml          = "cli.restore.only_check_whether_the_yaml"
	CliRestoreCannotReadFromTheLast            = "cli.restore.cannot_read_from_the_last"
	CliRestoreMakeSureItExistsIn               = "cli.restore.make_sure_it_exists_in"
	CliRestoreInTheLastCommitIs                = "cli.restore.in_the_last_commit_is"
	CliRestoreTheBaselineForRestoringIs        = "cli.restore.the_baseline_for_restoring_is"
	CliRestoreFirstCommitAVersionThat          = "cli.restore.first_commit_a_version_that"
	CliRestoreThisIsNotAGit                    = "cli.restore.this_is_not_a_git"
	CliRestoreBrickkitRestorePutsTheConfig     = "cli.restore.brickkit_restore_puts_the_config"
	CliRestoreIfYouWantToNarrow                = "cli.restore.if_you_want_to_narrow"
	CliRestoreErrorAConflictIsBeing            = "cli.restore.error_a_conflict_is_being"
	CliRestoreBrickkitRestoreHasToRead         = "cli.restore.brickkit_restore_has_to_read"
	CliRestoreErrorThisRepositoryHasNo         = "cli.restore.error_this_repository_has_no"
	CliRestoreTheBaselineForRestoringIs2       = "cli.restore.the_baseline_for_restoring_is_2"
	CliRestoreErrorIsNotInsideThis             = "cli.restore.error_is_not_inside_this"
	CliRestoreConfig                           = "cli.restore.config"
	CliRestoreErrorIsNotTrackedBy              = "cli.restore.error_is_not_tracked_by"
	CliRestoreFirstRunGitAddAnd                = "cli.restore.first_run_git_add_and"
	CliRestoreErrorThereAreStagedChanges       = "cli.restore.error_there_are_staged_changes"
	CliRestoreRestoreMovesTheSourceDirectories = "cli.restore.restore_moves_the_source_directories"
	CliRestoreFirstDealWithTheStaging          = "cli.restore.first_deal_with_the_staging"
	CliRestoreErrorTheSourceOfSome             = "cli.restore.error_the_source_of_some"
	CliRestoreAnd                              = "cli.restore.and"
	CliRestoreAComponentIdCanHave              = "cli.restore.a_component_id_can_have"
	CliRestoreFirstCheckWhatEachOf             = "cli.restore.first_check_what_each_of"
	CliRestoreWhenBothPlacesHaveSource         = "cli.restore.when_both_places_have_source"
	CliRestoreMatchesTheLastCommit             = "cli.restore.matches_the_last_commit"
	CliRestoreEnabledRestoredFromTheLast       = "cli.restore.enabled_restored_from_the_last"
	CliRestoreSLeftAsIsThis                    = "cli.restore.s_left_as_is_this"
	CliRestoreNotSet                           = "cli.restore.not_set"
	CliRestoreRemoveTheFieldTheCommit          = "cli.restore.remove_the_field_the_commit"
	CliRestoreError                            = "cli.restore.error"
)
