package msgid

// internal/cli/init.go
const (
	CliInitProject                        = "cli.init.project"
	CliInitProjectConfig                  = "cli.init.project_config"
	CliInitLocationsSearched              = "cli.init.locations_searched"
	CliInitCliWorkingDirectory            = "cli.init.cli_working_directory"
	CliInitInitProjectName                = "cli.init.init_project_name"
	CliInitAiAssistantProjectGuide        = "cli.init.ai_assistant_project_guide"
	CliInitAiAssistantSkills              = "cli.init.ai_assistant_skills"
	CliInitCheckTheComponentLayoutBefore  = "cli.init.check_the_component_layout_before"
	CliInitErrorFailedToInstallThe        = "cli.init.error_failed_to_install_the"
	CliInitErrorThisIsNotA                = "cli.init.error_this_is_not_a"
	CliInitAPreCommitHookCan              = "cli.init.a_pre_commit_hook_can"
	CliInitErrorTheProjectRootIs          = "cli.init.error_the_project_root_is"
	CliInitShort                          = "cli.init.short"
	CliInitAlreadyExistsLeftUnchanged     = "cli.init.already_exists_left_unchanged"
	CliInitRunGitInitFirstThen            = "cli.init.run_git_init_first_then"
	CliInitProjectInitialized             = "cli.init.project_initialized"
	CliInitBrickkitUpStartEverythingIn    = "cli.init.brickkit_up_start_everything_in"
	CliInitAfterFixingThePermissionsRun   = "cli.init.after_fixing_the_permissions_run"
	CliInitComponentSourceConfiguredAsThe = "cli.init.component_source_configured_as_the"
	CliInitDonTInstallTheAi               = "cli.init.don_t_install_the_ai"
	CliInitTheProjectItselfHasBeen        = "cli.init.the_project_itself_has_been"
	CliInitBrickkitAddPeopleBasicAdd      = "cli.init.brickkit_add_people_basic_add"
	CliInitYouCanAlsoDoWithout            = "cli.init.you_can_also_do_without"
	CliInitBrickkitInitHooksOnlyInstalls  = "cli.init.brickkit_init_hooks_only_installs"
	CliInitOnlyInstallThePreCommit        = "cli.init.only_install_the_pre_commit"
	CliInitErrorThereIsNoHere             = "cli.init.error_there_is_no_here"
	CliInitBrickkitAddLocalAddEvery       = "cli.init.brickkit_add_local_add_every"
	CliInitThePreCommitHookWas            = "cli.init.the_pre_commit_hook_was"
	CliInitWhenOneRepositoryHoldsSeveral  = "cli.init.when_one_repository_holds_several"
	CliInitIfComponentSourceGoesInto      = "cli.init.if_component_source_goes_into"
	CliInitThePreCommitHookHas            = "cli.init.the_pre_commit_hook_has"
	CliInitFirstRunBrickkitInitProject    = "cli.init.first_run_brickkit_init_project"
	CliInitExample                        = "cli.init.example"
	CliInitLong                           = "cli.init.long"
)
