package msgid

// internal/config
const (
	ConfigActionReadFile             = "config.action.read_file"
	ConfigProjectNameRule            = "config.project_name_rule"
	ConfigProjectNameMissing         = "config.project_name_missing"
	ConfigProjectNameInvalid         = "config.project_name_invalid"
	ConfigLabelProjectName           = "config.label.project_name"
	ConfigLabelNamingRule            = "config.label.naming_rule"
	ConfigHintUseName                = "config.hint.use_name"
	ConfigProjectNameTooLong         = "config.project_name_too_long"
	ConfigProjectNameHasSpace        = "config.project_name_has_space"
	ConfigProjectNameEdgeHyphen      = "config.project_name_edge_hyphen"
	ConfigProjectNameHasUpper        = "config.project_name_has_upper"
	ConfigProjectNameIllegalChar     = "config.project_name_illegal_char"
	ConfigProjectNameProblemWithRule = "config.project_name_problem_with_rule"
	ConfigNamespaceSameRule          = "config.namespace_same_rule"
	ConfigProjectExists              = "config.project_exists"
	ConfigLabelExisting              = "config.label.existing"
	ConfigPodSecurityOnly            = "config.pod_security_only"
	ConfigAllowFromNamespaceMissing  = "config.allow_from_namespace_missing"
	ConfigPortInvalid                = "config.port_invalid"
	ConfigEgressBothNamespaceAndCIDR = "config.egress_both_namespace_and_cidr"
	ConfigEgressNoTarget             = "config.egress_no_target"
	ConfigEntryOrdinal               = "config.entry_ordinal"
	ConfigVersionNotExactRange       = "config.version_not_exact_range"
	ConfigComponentDuplicate         = "config.component_duplicate"
	ConfigLocalPortConflict          = "config.local_port_conflict"
	ConfigExposePortNeedsExpose      = "config.expose_port_needs_expose"
	ConfigExposePortConflict         = "config.expose_port_conflict"
	ConfigTLSSecretNeedsExpose       = "config.tls_secret_needs_expose"
	ConfigHostnameMissing            = "config.hostname_missing"
	ConfigReplicasTooSmall           = "config.replicas_too_small"
	ConfigReplicasWithLocal          = "config.replicas_with_local"
	ConfigModeK8sUnsupported         = "config.mode_k8s_unsupported"
)
