package msgid

// internal/configdir（config/ 目录：公共变量、组件配置、冲突标记、解析、骨架）的文案。
const (
	ConfigdirValueUnencodable     = "configdir.value_unencodable"
	ConfigdirVarRefBadName        = "configdir.var_ref_bad_name"
	ConfigdirFileRefEmpty         = "configdir.file_ref_empty"
	ConfigdirKeyInvalid           = "configdir.key_invalid"
	ConfigdirVarsNoChain          = "configdir.vars_no_chain"
	ConfigdirConflictTitle        = "configdir.conflict_title"
	ConfigdirConflictLineLabel    = "configdir.conflict_line_label"
	ConfigdirConflictCurrent      = "configdir.conflict_current"
	ConfigdirConflictProposed     = "configdir.conflict_proposed"
	ConfigdirConflictHintEdit     = "configdir.conflict_hint_edit"
	ConfigdirConflictHintNoFormat = "configdir.conflict_hint_no_format"
	ConfigdirConflictTipEditor    = "configdir.conflict_tip_editor"
	ConfigdirConflictBlockNote    = "configdir.conflict_block_note"
	ConfigdirUnknownKey           = "configdir.unknown_key"
	ConfigdirUnknownKeyGuess      = "configdir.unknown_key_guess"
	ConfigdirLabelDeclared        = "configdir.label_declared"
	ConfigdirNoSchema             = "configdir.no_schema"
	ConfigdirLabelIgnoredKeys     = "configdir.label_ignored_keys"
	ConfigdirSecretRefNotSecret   = "configdir.secret_ref_not_secret"
	ConfigdirUndefinedVar         = "configdir.undefined_var"
	ConfigdirLabelUndefinedRef    = "configdir.label_undefined_ref"
	ConfigdirHintDefineVar        = "configdir.hint_define_var"
	ConfigdirSkeletonIntro        = "configdir.skeleton_intro"
	ConfigdirSkeletonRequired     = "configdir.skeleton_required"
	ConfigdirSkeletonOptional     = "configdir.skeleton_optional"
	ConfigdirSkeletonDefault      = "configdir.skeleton_default"
	ConfigdirSecretRefMalformed   = "configdir.secret_ref_malformed"
)
