package msgid

// internal/k8s
const (
	K8sActionCleanDir                    = "k8s.action.clean_dir"
	K8sPrivilegedPort                    = "k8s.privileged_port"
	K8sLabelPort                         = "k8s.label.port"
	K8sPrivilegedPortReasonDetail        = "k8s.privileged_port_reason_detail"
	K8sHintUsePortAbove1024              = "k8s.hint.use_port_above_1024"
	K8sHintDropPodSecurity               = "k8s.hint.drop_pod_security"
	K8sRefServedBy                       = "k8s.ref_served_by"
	K8sHeaderFile                        = "k8s.header.file"
	K8sRenderFailed                      = "k8s.render_failed"
	K8sHostnameMissing                   = "k8s.hostname_missing"
	K8sHostnameMissingReasonDetail       = "k8s.hostname_missing_reason_detail"
	K8sHintAddHostname                   = "k8s.hint.add_hostname"
	K8sHintExposeOnlyForExternal         = "k8s.hint.expose_only_for_external"
	K8sHostnameConflict                  = "k8s.hostname_conflict"
	K8sHostnameConflictReasonDetail      = "k8s.hostname_conflict_reason_detail"
	K8sHintChangeHostname                = "k8s.hint.change_hostname"
	K8sHintDropExpose                    = "k8s.hint.drop_expose"
	K8sEnvVarsUndefined                  = "k8s.env_vars_undefined"
	K8sLabelMissingVars                  = "k8s.label.missing_vars"
	K8sEnvVarsReasonDetail               = "k8s.env_vars_reason_detail"
	K8sHintDefineEnvVars                 = "k8s.hint.define_env_vars"
	K8sHintEnvVarDefault                 = "k8s.hint.env_var_default"
	K8sIngressControllerNamespaceMissing = "k8s.ingress_controller_namespace_missing"
	K8sLabelExposedComponent             = "k8s.label.exposed_component"
	K8sRefExposed                        = "k8s.ref_exposed"
	K8sIngressControllerReasonDetail     = "k8s.ingress_controller_reason_detail"
	K8sHintFindControllerNamespace       = "k8s.hint.find_controller_namespace"
	K8sHintThenWriteBrickkitYAML         = "k8s.hint.then_write_brickkit_yaml"
	K8sHintDropNetworkPolicy             = "k8s.hint.drop_network_policy"
	K8sEgressMissingLocation             = "k8s.egress_missing_location"
	K8sLabelResourceUndeclared           = "k8s.label.resource_undeclared"
	K8sEgressResourceUsers               = "k8s.egress_resource_users"
	K8sEgressReasonDetail                = "k8s.egress_reason_detail"
	K8sHintEgressAddLocation             = "k8s.hint.egress_add_location"
	K8sEgressExampleInCluster            = "k8s.egress_example_in_cluster"
	K8sHintEgressOutsideCluster          = "k8s.hint.egress_outside_cluster"
	K8sHintDropEgress                    = "k8s.hint.drop_egress"
	K8sServedMigrationReasonDetail       = "k8s.served_migration_reason_detail"
	K8sServedHealthCheckReasonDetail     = "k8s.served_health_check_reason_detail"
	K8sServedFieldsReasonDetail          = "k8s.served_fields_reason_detail"
)
