package msgid

// internal/project（三层文件装载与跨文件一致性）的文案。
const (
	ProjectDeployMissing           = "project.deploy_missing"
	ProjectDeployMissingHint       = "project.deploy_missing_hint"
	ProjectLocalFileMissing        = "project.local_file_missing"
	ProjectDeployFileNotFound      = "project.deploy_file_not_found"
	ProjectLocalStale              = "project.local_stale"
	ProjectLocalStaleReason        = "project.local_stale_reason"
	ProjectHintLocalRefresh        = "project.hint_local_refresh"
	ProjectHintLocalEdit           = "project.hint_local_edit"
	ProjectHintLocalOff            = "project.hint_local_off"
	ProjectDeployInconsistent      = "project.deploy_inconsistent"
	ProjectHintDeploySync          = "project.hint_deploy_sync"
	ProjectHintDeployEdit          = "project.hint_deploy_edit"
	ProjectLabelMissingEntry       = "project.label_missing_entry"
	ProjectLabelExtraEntry         = "project.label_extra_entry"
	ProjectMembersOnNonShell       = "project.members_on_non_shell"
	ProjectMemberUndeclared        = "project.member_undeclared"
	ProjectMemberIsShell           = "project.member_is_shell"
	ProjectMemberMultiVersion      = "project.member_multi_version"
	ProjectMemberTwoShells         = "project.member_two_shells"
	ProjectConfigAmbiguous         = "project.config_ambiguous"
	ProjectHintConfigAmbiguous     = "project.hint_config_ambiguous"
	ProjectConfigOrphan            = "project.config_orphan"
	ProjectVarUndefined            = "project.var_undefined"
	ProjectConfigUnversionedUnused = "project.config_unversioned_unused"
	ProjectConfigNameCollisions    = "project.config_name_collisions"
	ProjectLabelCollision          = "project.label_collision"
	ProjectHintConfigCollisions    = "project.hint_config_collisions"
	ProjectHintVarOnlyInTeamDeploy = "project.hint_var_only_in_team_deploy"
	ProjectHostPortCollision       = "project.host_port_collision"
	ProjectLabelPortClaim          = "project.label_port_claim"
	ProjectHintHostPortPerVersion  = "project.hint_host_port_per_version"
	ProjectSkeletonDeclHeader      = "project.skeleton.decl_header"
	ProjectSkeletonSources         = "project.skeleton.sources"
	ProjectSkeletonLocalDirNote    = "project.skeleton.local_dir_note"
	ProjectSkeletonMoreSources     = "project.skeleton.more_sources"
	ProjectSkeletonDeployHeader    = "project.skeleton.deploy_header"
	ProjectSkeletonDeployTarget    = "project.skeleton.deploy_target"
	ProjectSkeletonVarsHeader      = "project.skeleton.vars_header"
	ProjectHintReinit              = "project.hint_reinit"
	ProjectGitignoreBrickkit       = "project.gitignore.brickkit"
	ProjectGitignoreLocalDeploy    = "project.gitignore.local_deploy"
	ProjectGitignoreSecrets        = "project.gitignore.secrets"
	ProjectGitignoreConfigArchive  = "project.gitignore.config_archive"
	ProjectGitignoreComponents     = "project.gitignore.components"
)
