package msgid

const (
	ReleaseNotARepo           = "release.not_a_repo"
	ReleaseHintGitInit        = "release.hint_git_init"
	ReleaseDirty              = "release.dirty"
	ReleaseLabelChanged       = "release.label_changed"
	ReleaseHintCommit         = "release.hint_commit"
	ReleaseNoUpstream         = "release.no_upstream"
	ReleaseLabelBranch        = "release.label_branch"
	ReleaseHintSetUpstream    = "release.hint_set_upstream"
	ReleaseUnpushed           = "release.unpushed"
	ReleaseLabelUnpushed      = "release.label_unpushed"
	ReleaseHintPush           = "release.hint_push"
	ReleaseTagElsewhere       = "release.tag_elsewhere"
	ReleaseLabelTagAt         = "release.label_tag_at"
	ReleaseLabelHead          = "release.label_head"
	ReleaseHintBumpVersion    = "release.hint_bump_version"
	ReleaseAlreadyReleased    = "release.already_released"
	ReleaseRemoteUnreachable  = "release.remote_unreachable"
	ReleaseHintRemote         = "release.hint_remote"
	ReleasePushFailed         = "release.push_failed"
	ReleaseLabelRollback      = "release.label_rollback"
	ReleaseRolledBack         = "release.rolled_back"
	ReleaseHintRetry          = "release.hint_retry"
	ReleaseHintDeleteTag      = "release.hint_delete_tag"
	ReleaseGitFailed          = "release.git_failed"
	ReleaseDetachedHead       = "release.detached_head"
	ReleaseHintCheckoutBranch = "release.hint_checkout_branch"
	ReleaseTagOnlyLocal       = "release.tag_only_local"
	ReleaseHintPushTag        = "release.hint_push_tag"
	ReleaseHintDropLocalTag   = "release.hint_drop_local_tag"
)
